[meta]
name        = "DesignBuilder"
description = "Clean up DesignBuilder folders known to collect models"
author      = "Bart"
version     = "1.0.0"

[[rules]]
path   = "%USERPROFILE%/Documents/DesignBuilder Data/Backup"
action = "trash"

[[rules]]
path   = "%PROGRAMDATA%/DesignBuilder/JobServer/Users/User"
action = "trash"
